<?php

if($this->helper('notification')->checkCookie()):


	$collection=$this->helper('notification')->getNotification();
	
	 
if(count($collection)):	
?>

<script type="text/javascript"> 
        jQuery(document).ready(function(){
          jQuery.colorbox({width:"30%", inline:true, href:"#subscribe"});
        }); 
</script>  
<div style="display:none">
<div id="subscribe"  class="test">
<?php foreach($collection as $rec):?>
<?php echo $rec->getNotificationContent();?>
<?php endforeach;?>
</div>
</div>
<?php endif; endif;?>